env:
  es6: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmsVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'
